apiVersion: v1
kind: Secret
metadata:
 name: db-secret
 namespace: data
type: Opaque
stringData:
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
  DB_URL: "postgresql://postgres:postgres@postgres-service:5432/devopsdb"
  POSTGRES_DB: "devopsdb"